#!/usr/bin/with-contenv bash

cat <<"EOF"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
         _               _
    __ _| |__   ___  ___| |_
   / _` | '_ \ / _ \/ __| __/
  | (_| | | | | (_) \__ \ |_
   \__, |_|_|_|\___/|___/\__|
   |___/      /   _ \
          (¯\| o (@) |/¯)
           \_  .___.  _/
            /   !_!   \
           /_.--._.--._\

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
EOF

# copy the default nzbget.conf if nzbget.conf is not already present
cp -n /usr/local/bin/nzbget.conf /config/nzbget.conf
chown abc:abc /config/nzbget.conf

# set custom config option
## set the web user if the variable is not empty
[[ ! -z "$NZBGET_WEB_USER" ]] && sed -i -E "s|^ControlUsername=.*$|ControlUsername=$NZBGET_WEB_USER|g" /config/nzbget.conf

## set the web pass if the variable is not empty
[[ ! -z "$NZBGET_WEB_PASS" ]] && sed -i -E "s|^ControlPassword=.*$|ControlPassword=$NZBGET_WEB_PASS|g" /config/nzbget.conf

## set the main dir
NZBGET_MAIN_DIR=${NZBGET_MAIN_DIR:-/downloads/nzb}
sed -i -E "s|^MainDir=.*$|MainDir=$NZBGET_MAIN_DIR|g" /config/nzbget.conf

## set the script dir
NZBGET_SCRIPT_DIR=${NZBGET_SCRIPT_DIR:-/usr/local/bin}
sed -i -E "s|^ScriptDir=.*$|ScriptDir=$NZBGET_SCRIPT_DIR|g" /config/nzbget.conf

## set the extensions dir to the post-processing script
sed -i -E "s|^Extensions=.*$|Extensions=nzbget-postprocess.sh|g" /config/nzbget.conf

# only chown the /downloads directory if it is not owned by abc:abc or abc:users
CHOWN_DIR=/downloads
DIR_OWNER=`stat -c "%U:%G" $CHOWN_DIR`
if [[ $DIR_OWNER != "abc:abc" && $DIR_OWNER != "abc:users" ]]
then
    echo "chowning $CHOWN_DIR please be patient"
    chown -R abc:abc $CHOWN_DIR
fi

# only chown the /config directory if it is not owned by abc:abc or abc:users
CHOWN_DIR=/config
DIR_OWNER=`stat -c "%U:%G" $CHOWN_DIR`
if [[ $DIR_OWNER != "abc:abc" && $DIR_OWNER != "abc:users" ]]
then
    echo "chowning $CHOWN_DIR please be patient"
    chown -R abc:abc $CHOWN_DIR
fi
